Feat 442 cancel edit post
Journaly/journaly pull request #613
Opened 2021-07-13 12:48 UTC by dom-waterson

## Description

Add a "Cancel" Button to post editing experience

**Issue:** <#442>

Journaly.com profile url (include if you'd like the "code contributor" badge): https://github.com/dom-waterson

## Subtasks

- [x] I have added this PR to the Journaly Kanban project ✅
- [x] Added cancel button
- [x] Added confirmation modal
- [x] Added translations
- [x] On confirming: cleared out edit post localStorage data and reset to initial values

## Screenshots

![Screenshot 2021-07-13 at 13 39 33](https://user-images.githubusercontent.com/13645967/125452992-6b95bc16-45ee-48ed-bda4-2c4313a7e582.png)

![Screenshot 2021-07-13 at 13 40 18](https://user-images.githubusercontent.com/13645967/125453080-c9757e6a-41fe-4a4c-9f36-2d687a8d35e3.png)

2021-07-28 15:10 UTC, robin-macpherson requested changes
Great work @dom-waterson ! Everything looks good. The only thing I'd like to see added is redirecting them to the post page after cancelling (so just not in edit mode). See how we use the `useRouter` hook and `router.push()` on the `edit.tsx` page for an example

2021-07-28 22:08 UTC, dom-waterson commented
@robin-macpherson Thanks for going through this! I've updated to redirect the user back to post page on cancelling.

2021-07-29 16:56 UTC, Lanny approved these changes

2021-07-29 16:57 UTC, robin-macpherson approved these changes
Great stuff @dom-waterson ! Thanks for adding that last bit 🚀

2021-07-29 17:01 UTC, merged

2021-07-29 17:01 UTC, robin-macpherson commented
@dom-waterson was just going to give you the code contributor badge but realised you left your GitHub profile link in the PR description, not your Journaly profile link. Could you let me know your Journaly profile link instead and I'll get that badge added for you 😊

2021-07-29 17:08 UTC, dom-waterson commented
@robin-macpherson my bad! 🤦  Here it is: https://journaly.com/dashboard/profile/8647 Thanks 😄

2021-07-29 18:06 UTC, robin-macpherson commented
@dom-waterson haha no worries! You'll see the badge on your profile now 😄 It's nothing too flashy but in the coming months we'll be revamping the whole appearance of badges 🎖